GET http://localhost:8080/calculate?operand1=10&operator=+&operand2=55
->
GET http://localhost:8080/calculate?operand1=10&operator=%2b&operand2=55

URL 인코딩(퍼센트 인코딩)
-URL로 사용할 수 없는 문자(예약어, Non-ASCII문자=한글 등)를 사용할 수 있도록 인코딩
-인코딩 된 문자는 triplet(세 개가 한 세트)로 인코딩 되면 각각을 % 다음에 두 개의 16진수로 표현